/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static helpers.Logs.loggedIn;
import static helpers.Logs.parseLogs;
import static helpers.Logs.setUser;
import static helpers.Logs.username;

import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.LayoutStyle;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.event.PopupMenuEvent;
import javax.swing.event.PopupMenuListener;

import org.jdesktop.swingx.JXLabel;

import helpers.Loader;
import helpers.Teacher;

/**
 *
 * @author kapow
 */
@SuppressWarnings("serial")
public class Display extends JFrame {

	/**
     * Creates new form Display
     */
    public Display() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings("deprecation")
	private void initComponents() {

        results = new JDialog();
        jLayeredPane1 = new JLayeredPane();
        recordsReadoutPanel = new JPanel();
        okButton = new JButton();
        recordsReadoutTitleLabel = new JLabel();
        recordsReadoutXLabel = new org.jdesktop.swingx.JXLabel();
        resultsReadoutPanel = new JPanel();
        resultsReadoutTitleLabel = new JLabel();
        nextButton = new JButton();
        resultsReadoutXLabel = new org.jdesktop.swingx.JXLabel();
        jTabbedPane1 = new JTabbedPane();
        LoginPanel = new JPanel();
        firstNameLabel = new JLabel();
        firstNameTextField = new JTextField();
        loginButton = new JButton();
        userReadoutLabel = new JLabel();
        TestPanel = new JPanel();
        piTextField = new JTextField();
        instructionLabel = new JLabel();
        submitButton = new JButton();
        digitsInputTextField = new JTextField();
        jLabel1 = new JLabel();
        RecordsPanel = new JPanel();
        LogsPanel = new JPanel();
        allUsersToggleButton = new JToggleButton();
        jProgressBar1 = new JProgressBar();
        jScrollPane1 = new JScrollPane();
        logsReadoutPanel = new JPanel();
        datesXLabel = new org.jdesktop.swingx.JXLabel();
        timesXLabel = new org.jdesktop.swingx.JXLabel();
        recordsXLabel = new org.jdesktop.swingx.JXLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        sortingComboBox = new JComboBox<>();
        jLabel5 = new JLabel();
        advancedToggleButton = new JToggleButton();
        jProgressBar2 = new JProgressBar();
        advancedToggleButton2 = new JToggleButton();
        sortingComboBox2 = new JComboBox<String>();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        jScrollPane2 = new JScrollPane();
        datesXLabel2 = new JXLabel();
        timesXLabel2 = new JXLabel();
        recordsXLabel2 = new JXLabel();
        logsReadoutPanel2 = new JPanel();
        lockedToggleButton = new JToggleButton();

        results.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        results.setResizable(false);
        results.setSize(new Dimension(400, 275));
        results.setType(Window.Type.POPUP);

        okButton.setText("OK");
        okButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        recordsReadoutTitleLabel.setHorizontalAlignment(SwingConstants.CENTER);
        recordsReadoutTitleLabel.setText("Records");

        recordsReadoutXLabel.setHorizontalAlignment(SwingConstants.CENTER);
        recordsReadoutXLabel.setText("You are not logged in. No data available.");
        recordsReadoutXLabel.setLineWrap(true);

        GroupLayout recordsReadoutPanelLayout = new GroupLayout(recordsReadoutPanel);
        recordsReadoutPanel.setLayout(recordsReadoutPanelLayout);
        recordsReadoutPanelLayout.setHorizontalGroup(
            recordsReadoutPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(recordsReadoutPanelLayout.createSequentialGroup()
                .addGroup(recordsReadoutPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(recordsReadoutPanelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(okButton, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
                    .addGroup(recordsReadoutPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(recordsReadoutTitleLabel, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE))
                    .addGroup(recordsReadoutPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(recordsReadoutXLabel, GroupLayout.PREFERRED_SIZE, 260, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        recordsReadoutPanelLayout.setVerticalGroup(
            recordsReadoutPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(recordsReadoutPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(recordsReadoutTitleLabel)
                .addGap(30, 30, 30)
                .addComponent(recordsReadoutXLabel, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(okButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        resultsReadoutTitleLabel.setHorizontalAlignment(SwingConstants.CENTER);
        resultsReadoutTitleLabel.setText("Results");

        nextButton.setText("Next");
        nextButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        resultsReadoutXLabel.setHorizontalAlignment(SwingConstants.CENTER);
        resultsReadoutXLabel.setText("Error");
        resultsReadoutXLabel.setLineWrap(true);

        GroupLayout resultsReadoutPanelLayout = new GroupLayout(resultsReadoutPanel);
        resultsReadoutPanel.setLayout(resultsReadoutPanelLayout);
        resultsReadoutPanelLayout.setHorizontalGroup(
            resultsReadoutPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(resultsReadoutPanelLayout.createSequentialGroup()
                .addGroup(resultsReadoutPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(resultsReadoutPanelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(nextButton, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
                    .addGroup(resultsReadoutPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(resultsReadoutTitleLabel, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE))
                    .addGroup(resultsReadoutPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(resultsReadoutXLabel, GroupLayout.PREFERRED_SIZE, 260, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        resultsReadoutPanelLayout.setVerticalGroup(
            resultsReadoutPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(resultsReadoutPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(resultsReadoutTitleLabel)
                .addGap(30, 30, 30)
                .addComponent(resultsReadoutXLabel, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(nextButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(recordsReadoutPanel, 1);
        jLayeredPane1.setLayer(resultsReadoutPanel, 2);

        GroupLayout jLayeredPane1Layout = new GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(recordsReadoutPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(resultsReadoutPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(recordsReadoutPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(resultsReadoutPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        GroupLayout resultsLayout = new GroupLayout(results.getContentPane());
        results.getContentPane().setLayout(resultsLayout);
        resultsLayout.setHorizontalGroup(
            resultsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
        resultsLayout.setVerticalGroup(
            resultsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Learn Pi");
        setMinimumSize(new Dimension(500, 400));

        jTabbedPane1.setMinimumSize(new Dimension(529, 400));

        LoginPanel.addComponentListener(new ComponentAdapter() {
            public void componentShown(ComponentEvent evt) {
                setFirstNameDefault(evt);
                LoginPanelComponentShown(evt);
            }
        });

        firstNameLabel.setText("First Name:");

        firstNameTextField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        loginButton.setText("Login");
        loginButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        userReadoutLabel.setHorizontalAlignment(SwingConstants.TRAILING);
        userReadoutLabel.setText("Not logged in");

        GroupLayout LoginPanelLayout = new GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(firstNameLabel)
                        .addGap(10, 10, 10)
                        .addComponent(firstNameTextField, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(loginButton)))
                .addGap(157, 157, 157))
            .addGroup(GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                .addComponent(userReadoutLabel, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userReadoutLabel)
                .addGap(120, 120, 120)
                .addGroup(LoginPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(firstNameLabel))
                    .addComponent(firstNameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(loginButton))
        );

        jTabbedPane1.addTab("Login", new ImageIcon(getClass().getResource("/images/login_icon.png")), LoginPanel, "Save your records."); // NOI18N

        TestPanel.setMinimumSize(new Dimension(500, 400));
        TestPanel.addComponentListener(new ComponentAdapter() {
            public void componentShown(ComponentEvent evt) {
                setPiTextFieldDefault(evt);
            }
        });

        piTextField.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        piTextField.setNextFocusableComponent(digitsInputTextField);
        piTextField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                piTextFieldActionPerformed(evt);
            }
        });

        instructionLabel.setText("Type in known digits of pi.");

        submitButton.setText("Submit");
        submitButton.setToolTipText("Click when ready to submit the above String");
        submitButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        digitsInputTextField.setHorizontalAlignment(JTextField.TRAILING);
        digitsInputTextField.setText("3");
        digitsInputTextField.setToolTipText("Remeber to hit ENTER.");
        digitsInputTextField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                digitsInputTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("How many digits would you like to learn at a time.");

        GroupLayout TestPanelLayout = new GroupLayout(TestPanel);
        TestPanel.setLayout(TestPanelLayout);
        TestPanelLayout.setHorizontalGroup(
            TestPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(TestPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TestPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(piTextField)
                    .addGroup(GroupLayout.Alignment.TRAILING, TestPanelLayout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                        .addGroup(TestPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(TestPanelLayout.createSequentialGroup()
                                .addComponent(instructionLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(TestPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(digitsInputTextField, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))))
                    .addGroup(GroupLayout.Alignment.TRAILING, TestPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TestPanelLayout.setVerticalGroup(
            TestPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(TestPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(instructionLabel)
                .addGap(48, 48, 48)
                .addComponent(piTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(submitButton)
                .addGap(50, 50, 50)
                .addGroup(TestPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(digitsInputTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Test", new ImageIcon(getClass().getResource("/images/test_icon.png")), TestPanel, "Test what you know and learn more."); // NOI18N

        RecordsPanel.addComponentListener(new ComponentAdapter() {
            public void componentShown(ComponentEvent evt) {
                RecordsPanelComponentShown(evt);
            }
        });

        allUsersToggleButton.setText("All Users");
        allUsersToggleButton.setToolTipText("Toggle off to see only your records.");
        allUsersToggleButton.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                allUsersToggleButtonItemStateChanged(evt);
            }
        });

        jProgressBar1.setFocusable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        logsReadoutPanel.setMinimumSize(new Dimension(390, 250));

        datesXLabel.setHorizontalAlignment(SwingConstants.CENTER);
        datesXLabel.setText("User should");
        datesXLabel.setVerticalAlignment(SwingConstants.TOP);
        datesXLabel.setTextAlignment(org.jdesktop.swingx.JXLabel.TextAlignment.CENTER);

        timesXLabel.setHorizontalAlignment(SwingConstants.CENTER);
        timesXLabel.setText("not");
        timesXLabel.setVerticalAlignment(SwingConstants.TOP);
        timesXLabel.setTextAlignment(org.jdesktop.swingx.JXLabel.TextAlignment.CENTER);

        recordsXLabel.setHorizontalAlignment(SwingConstants.CENTER);
        recordsXLabel.setText("see this");
        recordsXLabel.setVerticalAlignment(SwingConstants.TOP);
        recordsXLabel.setTextAlignment(org.jdesktop.swingx.JXLabel.TextAlignment.CENTER);

        GroupLayout logsReadoutPanelLayout = new GroupLayout(logsReadoutPanel);
        logsReadoutPanel.setLayout(logsReadoutPanelLayout);
        logsReadoutPanelLayout.setHorizontalGroup(
            logsReadoutPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(logsReadoutPanelLayout.createSequentialGroup()
                .addComponent(datesXLabel, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timesXLabel, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recordsXLabel, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        logsReadoutPanelLayout.setVerticalGroup(
            logsReadoutPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, logsReadoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logsReadoutPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(datesXLabel, GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(timesXLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recordsXLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        jScrollPane1.setViewportView(logsReadoutPanel);

        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setText("Date");

        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel3.setText("Record");

        jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel4.setText("Time");

        sortingComboBox.setModel(new DefaultComboBoxModel<>(new String[] { "Newest to Oldest", "Oldest to Newest" }));
        sortingComboBox.addPopupMenuListener(new PopupMenuListener() {
            public void popupMenuCanceled(PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(PopupMenuEvent evt) {
                sortingComboBoxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(PopupMenuEvent evt) {
            }
        });

        jLabel5.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel5.setText("Sort by:");

        advancedToggleButton.setText("Advanced");
        advancedToggleButton.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                advancedToggleButtonItemStateChanged(evt);
            }
        });

        GroupLayout RecordsPanelLayout = new GroupLayout(RecordsPanel);
        RecordsPanel.setLayout(RecordsPanelLayout);
        RecordsPanelLayout.setHorizontalGroup(
            RecordsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(RecordsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RecordsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(RecordsPanelLayout.createSequentialGroup()
                        .addGroup(RecordsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(sortingComboBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(advancedToggleButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(allUsersToggleButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RecordsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(RecordsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        RecordsPanelLayout.setVerticalGroup(
            RecordsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(RecordsPanelLayout.createSequentialGroup()
                .addGroup(RecordsPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(RecordsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
                        .addComponent(allUsersToggleButton)
                        .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RecordsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
                    .addGroup(RecordsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sortingComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(advancedToggleButton)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jProgressBar1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Records", new ImageIcon(getClass().getResource("/images/logs_icon.png")), RecordsPanel, "Veiw your record along with local records."); // NOI18N
        
        
        //TODO Configure LogsPanel
        LogsPanel.addComponentListener(new ComponentAdapter() {
            public void componentShown(ComponentEvent evt) {
                LogsPanelComponentShown(evt);
            }
        });
        
        lockedToggleButton.setText("All Users");
        lockedToggleButton.setToolTipText("Toggle off to see only your records.");
        lockedToggleButton.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                lockedToggleButtonItemStateChanged(evt);
            }
        });

        jProgressBar2.setFocusable(false);

        jScrollPane2.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        logsReadoutPanel2.setMinimumSize(new Dimension(390, 250));

        datesXLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        datesXLabel2.setText("User should");
        datesXLabel2.setVerticalAlignment(SwingConstants.TOP);
        datesXLabel2.setTextAlignment(org.jdesktop.swingx.JXLabel.TextAlignment.CENTER);

        timesXLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        timesXLabel2.setText("not");
        timesXLabel2.setVerticalAlignment(SwingConstants.TOP);
        timesXLabel2.setTextAlignment(org.jdesktop.swingx.JXLabel.TextAlignment.CENTER);

        recordsXLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        recordsXLabel2.setText("see this");
        recordsXLabel2.setVerticalAlignment(SwingConstants.TOP);
        recordsXLabel2.setTextAlignment(org.jdesktop.swingx.JXLabel.TextAlignment.CENTER);

        jScrollPane2.setViewportView(logsReadoutPanel2);

        jLabel6.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel6.setText("Date");

        jLabel7.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel7.setText("Record");

        jLabel8.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel8.setText("Time");

        sortingComboBox2.setModel(new DefaultComboBoxModel<>(new String[] { "Newest to Oldest", "Oldest to Newest" }));
        sortingComboBox2.addPopupMenuListener(new PopupMenuListener() {
            public void popupMenuCanceled(PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(PopupMenuEvent evt) {
                sortingComboBoxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(PopupMenuEvent evt) {
            }
        });

        jLabel9.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel9.setText("Sort by:");

        advancedToggleButton2.setText("Advanced");
        advancedToggleButton2.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                advancedToggleButtonItemStateChanged(evt);
            }
        });

        GroupLayout LogsPanelLayout = new GroupLayout(LogsPanel);
        LogsPanel.setLayout(LogsPanelLayout);
		LogsPanelLayout.setHorizontalGroup(
            LogsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(LogsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LogsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LogsPanelLayout.createSequentialGroup()
                        .addGroup(LogsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(sortingComboBox2, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(advancedToggleButton2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lockedToggleButton , GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(LogsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(LogsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        LogsPanelLayout.setVerticalGroup(
            LogsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(LogsPanelLayout.createSequentialGroup()
                .addGroup(LogsPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(LogsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
                        .addComponent(lockedToggleButton)
                        .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LogsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
                    .addGroup(LogsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sortingComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(advancedToggleButton2)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jProgressBar2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Complete Log", new ImageIcon(getClass().getResource("/images/logs_icon.png")), LogsPanel, "Veiw all of your attempts."); // NOI18N

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 515, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 424, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogsPanelComponentShown(ComponentEvent evt) {// GEN-FIRST:event_RecordsPanelComponentShown
        if (loggedIn) {
        	LogsPanel.setEnabled(true);
        } else {
        	LogsPanel.setEnabled(false);
        }
        datesXLabel2.setLineWrap(true);
        timesXLabel2.setLineWrap(true);
        recordsXLabel2.setLineWrap(true);
        inName = username;
        mode = "NORMAL";
        advanced = false;
        updateLogsReadouts();
    }

	private void advancedToggleButtonItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_advancedToggleButtonItemStateChanged
        advanced = advancedToggleButton.isSelected();
        updateRecordsReadouts();
        updateLogsReadouts();
    }//GEN-LAST:event_advancedToggleButtonItemStateChanged

    private void sortingComboBoxPopupMenuWillBecomeInvisible(PopupMenuEvent evt) {//GEN-FIRST:event_sortingComboBoxPopupMenuWillBecomeInvisible
        int selected = sortingComboBox.getSelectedIndex();
        if(selected == 0)
            mode = "NORMAL";
        else if (selected == 1)
        	mode = "REVERSE";
        updateRecordsReadouts();
    }//GEN-LAST:event_sortingComboBoxPopupMenuWillBecomeInvisible

    private void nextButtonActionPerformed(ActionEvent evt) {// GEN-FIRST:event_nextButtonActionPerformed
        jLayeredPane1.setLayer(resultsReadoutPanel, 0);
        results.getRootPane().setDefaultButton(okButton);
    }// GEN-LAST:event_nextButtonActionPerformed

    private void digitsInputTextFieldActionPerformed(ActionEvent evt) {// GEN-FIRST:event_digitsInputTextFieldActionPerformed
        try {
            Teacher.digitsPerTry = Integer.parseInt(digitsInputTextField.getText());
            System.out.println(Teacher.digitsPerTry);
        } catch (NumberFormatException e) {
            Teacher.digitsPerTry = 3;
        }
    }// GEN-LAST:event_digitsInputTextFieldActionPerformed

    private void piTextFieldActionPerformed(ActionEvent evt) {// GEN-FIRST:event_piTextFieldActionPerformed
        submitButtonActionPerformed(evt);
    }// GEN-LAST:event_piTextFieldActionPerformed

    private void setPiTextFieldDefault(ComponentEvent evt) {// GEN-FIRST:event_setPiTextFieldDefault
        piTextField.requestFocus();
    }// GEN-LAST:event_setPiTextFieldDefault

    private void setFirstNameDefault(ComponentEvent evt) {// GEN-FIRST:event_setFirstNameDefault
        firstNameTextField.requestFocus();
    }// GEN-LAST:event_setFirstNameDefault

    private void firstNameTextFieldActionPerformed(ActionEvent evt) {// GEN-FIRST:event_firstNameTextFieldActionPerformed
        loginButtonActionPerformed(evt);
    }// GEN-LAST:event_firstNameTextFieldActionPerformed

    private void RecordsPanelComponentShown(ComponentEvent evt) {// GEN-FIRST:event_RecordsPanelComponentShown
        if (loggedIn) {
            allUsersToggleButton.setEnabled(true);
        } else {
            allUsersToggleButton.setEnabled(false);
        }
        datesXLabel.setLineWrap(true);
        timesXLabel.setLineWrap(true);
        recordsXLabel.setLineWrap(true);
        inName = username;
        mode = "NORMAL";
        advanced = false;
        updateRecordsReadouts();
    }// GEN-LAST:event_RecordsPanelComponentShown

    private void LoginPanelComponentShown(ComponentEvent evt) {// GEN-FIRST:event_LoginPanelComponentShown
        if (loggedIn) {
            userReadoutLabel.setText(generateFriendlyUsername());
        } else {
            userReadoutLabel.setText("Not logged in");
        }
    }// GEN-LAST:event_LoginPanelComponentShown

    private void allUsersToggleButtonItemStateChanged(ItemEvent evt) {// GEN-FIRST:event_allUsersToggleButtonItemStateChanged
        if (allUsersToggleButton.isSelected()) {
            inName = "WORLD";
        } else {
        	inName = username;
        }
        updateRecordsReadouts();
    }// GEN-LAST:event_allUsersToggleButtonItemStateChanged

    private void lockedToggleButtonItemStateChanged(ItemEvent evt) {
    	
    }

    private void submitButtonActionPerformed(ActionEvent evt) {// GEN-FIRST:event_submitActionPerformed
        Teacher.test(piTextField.getText());
        piTextField.setText(null);
        resultsReadoutXLabel.setText(Teacher.teach());
        results.setSize(400, 300);
        results.setVisible(true);
        results.getRootPane().setDefaultButton(nextButton);
        Teacher.setRecords(recordsReadoutXLabel);
    }

    private void loginButtonActionPerformed(ActionEvent evt) {
        if (!loggedIn) {
            try {
                setUser(firstNameTextField.getText());
                if (!Loader.isUser(username)) {
                    Loader.createRecordFile(username);
                }
                firstNameTextField.setText("");
                userReadoutLabel.setText(generateFriendlyUsername());
                loginButton.setText("Logout");
            } catch (IOException ex) {
                Logger.getLogger(Display.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            loggedIn = false;
            loginButton.setText("Login");
            userReadoutLabel.setText("Not logged in");
        }
    }

    private void okButtonActionPerformed(ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        jLayeredPane1.setLayer(resultsReadoutPanel, 2);
        results.setVisible(false);
    }

    public static void runDisplay() {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting
        // code (optional) ">
        /*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        // </editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() -> {
            new Display().setVisible(true);
        });
    }
    
    private void updateLogsReadouts() {
    	List<String> logs = parseLogs(inName, mode, advanced, false);
        datesXLabel2.setText(logs.get(0));
        timesXLabel2.setText(logs.get(1));
        recordsXLabel2.setText(logs.get(2));
    }
    
    public void updateRecordsReadouts() {
    	List<String> logs = parseLogs(inName, mode, advanced, true);
        datesXLabel.setText(logs.get(0));
        timesXLabel.setText(logs.get(1));
        recordsXLabel.setText(logs.get(2));
    }

    private String generateFriendlyUsername() {
        String name = username, firstLetter, theRest;
        firstLetter = name.substring(0, 1);
        theRest = name.substring(1).toLowerCase();
        return firstLetter + theRest;
    }
    
    private String inName, mode;
    private boolean advanced;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel LoginPanel;
    private JPanel RecordsPanel;
    private JPanel LogsPanel;
    private JPanel TestPanel;
    private JToggleButton advancedToggleButton;
    private JToggleButton allUsersToggleButton;
    private JXLabel datesXLabel;
    private JXLabel timesXLabel;
    private JTextField digitsInputTextField;
    private JLabel firstNameLabel;
    private JTextField firstNameTextField;
    private JLabel instructionLabel;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLayeredPane jLayeredPane1;
    private JProgressBar jProgressBar1;
    private JScrollPane jScrollPane1;
    private JTabbedPane jTabbedPane1;
    private JButton loginButton;
    private JPanel logsReadoutPanel;
    private JButton nextButton;
    private JButton okButton;
    private JTextField piTextField;
    private JPanel recordsReadoutPanel;
    private JLabel recordsReadoutTitleLabel;
    private JXLabel recordsReadoutXLabel;
    private JXLabel recordsXLabel;
    private JDialog results;
    private JPanel resultsReadoutPanel;
    private JLabel resultsReadoutTitleLabel;
    private JXLabel resultsReadoutXLabel;
    private JComboBox<String> sortingComboBox;
    private JButton submitButton;
    private JLabel userReadoutLabel;
    private JProgressBar jProgressBar2;
    private JToggleButton advancedToggleButton2;
    private JComboBox<String> sortingComboBox2;
    private JLabel jLabel6, jLabel7, jLabel8, jLabel9;
    private JScrollPane jScrollPane2;
    private JXLabel datesXLabel2, timesXLabel2, recordsXLabel2;
    private JPanel logsReadoutPanel2;
    private JToggleButton lockedToggleButton;
    // End of variables declaration//GEN-END:variables
}
